### PR TITLE
Fix 91 fix reset button makarchenkov

### PR DESCRIPTION
**Pull request by vitaliimak**

### CODE REVIEW

**Review by Andrii35 — DISMISSED** [review]
It works well

**Review by narekacy — CHANGES_REQUESTED** [review]
It works Ok. But, when in refreshes info in 'Categories', we need 'Select' button no more. We can't reach its functionality. So we need to remove this button from UI.

**Comment by vitaliimak** [comment]
@narekacy thanks for review! You are right, I've broken previous functionality. So I've returned possibility to use button `Select` in `Categories`

**Review by narekacy — APPROVED** [review]

**Review by r-yevchuk — APPROVED** [review]

**Review by Melnyk9506 — APPROVED** [review]

**Comment by Melnyk9506** [comment]
works well

**Pull request merged**
