### PR TITLE
Feature 88 setup staging server makarchenkov

### PR DESCRIPTION
**Pull request by vitaliimak**
Stagin server doesn't work before merging PR
http://35.234.68.126

### CODE REVIEW

**Comment by narekacy** [comment]
It seems that I have style issues on Restaurants page:

image

**Review by Andrii35 — DISMISSED** [review]
App run ok!

**Review by narekacy — DISMISSED** [review]
Works Ok

**Comment by vitaliimak** [comment]
@narekacy I've created fix task https://trello.com/c/npjTQEiK/119-111-fix-restaurant-page-style

**Review by Melnyk9506 — COMMENTED** [review]
pleace add link to PR
 No description provided.

**Comment by vitaliimak** [comment]
@Melnyk9506 Done

**Review by narekacy — APPROVED** [review]
Good job!

**Review by Melnyk9506 — APPROVED** [review]
Plus one approve

**Review by Andrii35 — APPROVED** [review]

**Pull request merged**
