### PR TITLE
Fix 166 back-end validation for uploaded image

### PR DESCRIPTION
**Pull request by r-yevchuk**

### CODE REVIEW

**Comment by narekacy** [comment]
I upload **[this](https://commons.wikimedia.org/wiki/File:Pizigani_1367_Chart_10MB.jpg)** to Profile image and I have no restrictions for it.

**Comment by VozNick** [comment]
> I upload **[this](https://commons.wikimedia.org/wiki/File:Pizigani_1367_Chart_10MB.jpg)** to Profile image and I have no restrictions for it.

You uploaded via avatar on person page?
..it crops a file there..

**Comment by narekacy** [comment]
> You uploaded via avatar on person page?
> ..it crops a file there..

I mean Profile image. If it crops there, why we need this validation?) We can crop it everywhere to minimal suitable sizes

**Comment by VozNick** [comment]
> > You uploaded via avatar on person page?
> > ..it crops a file there..
> 
> I mean Profile image. If it crops there, why we need this validation?) We can crop it everywhere to minimal suitable sizes

but if not?

**Comment by narekacy** [comment]
> > > You uploaded via avatar on person page?
> > > ..it crops a file there..
> > 
> > 
> > I mean Profile image. If it crops there, why we need this validation?) We can crop it everywhere to minimal suitable sizes
> 
> but if not?



Sorry, can't understand you. What do you mean?)

**Comment by VozNick** [comment]
thats why we put all validations in server because we can make without valitation.
my photos don't use crop, instead I made validation on front (no more than 5 mb), and for security we do it on server

**Comment by VozNick** [comment]
restaurant photos don't have crop, but have validation no more 5 mb

**Comment by narekacy** [comment]
> restaurant photos don't have crop, but have validation no more 5 mb

So we have validation only for restaurant photos? This doesn't work in Profile image udloading

**Comment by r-yevchuk** [comment]
> > restaurant photos don't have crop, but have validation no more 5 mb
> 
> So we have validation only for restaurant photos? This doesn't work in Profile image udloading

We do not need validation for the profile image. The selected image is cropped on the frontend, and then sent to the server

**Review by Andrii35 — APPROVED** [review]

**Review by narekacy — APPROVED** [review]

**Review by Melnyk9506 — APPROVED** [review]

**Pull request merged**
