### PR TITLE
add migration to db. Add script for baseline scheme

### PR DESCRIPTION
**Pull request by VozNick**
Working database migration. Please check. If working, I recommend that it should be first merged to dev, because it has baseline migration. If smone will change db, with out this migration - it will broke.

### CODE REVIEW

**Review by vitaliimak — APPROVED** [review]
I don't understand what it does, but it works) In prod environment too

**Comment by vitaliimak** [comment]
@VozNick you should set other reviewers (team leads and quality control)
https://rv-054java.slack.com/archives/CUJ8B6RV4/p1587565758001400

**Review by Melnyk9506 — APPROVED** [review]
well done

**Comment by r-yevchuk** [comment]
Знімок екрану_2020-04-24_13-34-19
I can't start the project

**Review by r-yevchuk — APPROVED** [review]
It work well!

**Pull request merged**
