### PR TITLE
Feature 8 add menu view nazaruk

### PR DESCRIPTION
**Pull request by Andrii35**
After last demo not yet fixed Dropdown for dish categories.
JUnit test is created for POST methods in all my entities. Other will dane during this Sprint.
Inserted a button instead of the checkbox.

### CODE REVIEW

**Review by vitaliimak — CHANGES_REQUESTED** [review]
image
Please, remove this folder

**Comment by Andrii35** [comment]
> image
> Please, remove this folder

Fixed

**Comment by narekacy** [comment]
Everything is ok. It is better view now.
I will approve it. Next we need to create new task for minor fixes:

rename 'grn' to 'UAH' in dish price
menu-views/dish.js   -> lines 10-13:   I'd make ingredients font size less than dish's name
menu-views/menu-view   ->  line 16:   menuitemdishes - camelCase
MenuItemDishController  ->   line 23, 64:   menuitemdish
Dish Entity   ->   line 36:   categoryfood_id
MenuItemDish Entity   ->   line 45:   use primitive Boolean
Restaurant Entity   ->   line 24:   I am not sure that Restaurant name should be more than 15 symbols
DatabaseSeed   ->   liines 50-75:   We can just use @RequiredArgsConstructor here

**Review by narekacy — APPROVED** [review]

**Comment by Andrii35** [comment]
Thanks for review! I will take note and create task for minor issues.

**Review by VozNick — APPROVED** [review]

**Review by Melnyk9506 — APPROVED** [review]
well done

**Review by vitaliimak — APPROVED** [review]

**Pull request merged**
