### PR TITLE
Feature 168. Modify ordered menu dishes. narek

### PR DESCRIPTION
**Pull request by narekacy**
Now you add dishes in your restaurant order. You can also modify its quantity.

### CODE REVIEW

**Comment by vitaliimak** [comment]
@narekacy 
image
I've removed this line https://github.com/Social-projects-Rivne/Lunch_Time/pull/88/files#diff-71aed0e0d9c7b59392b58405d4874aa0R56
and error disappears

**Review by vitaliimak — DISMISSED** [review]
image

**Comment by narekacy** [comment]
> @narekacy
> image
> I've removed this line https://github.com/Social-projects-Rivne/Lunch_Time/pull/88/files#diff-71aed0e0d9c7b59392b58405d4874aa0R56
> and error disappears

Thanks, now I can fix it!

**Comment by narekacy** [comment]
@vitalii-mak First '-' and '+' were shown in one line. I don't know why it has changed. Will fix it now.

**Review by Andrii35 — DISMISSED** [review]

**Comment by vitaliimak** [comment]
@narekacy is this PR ready to review?

About question from first message
> Any ideas?

No

**Comment by narekacy** [comment]
> @narekacy is this PR ready to review?
> 
> About question from first message
> 
> > Any ideas?
> 
> No

The client can't see ordered dishes in response, but should. The rest works ok

**Review by Andrii35 — DISMISSED** [review]

**Comment by vitaliimak** [comment]
@Andrii35 why you approve this PR with conflict files?
@narekacy will you fix conflicts?
image

**Comment by narekacy** [comment]
> @Andrii35 why you approve this PR with conflict files?
> @narekacy will you fix conflicts?
> image

I guess @Andrii35 had approved this PR before another branch was merged. 

Sure, I will fix it right now, thanks!

**Comment by vitaliimak** [comment]
> I guess @Andrii35 had approved this PR before another branch was merged.

Conflicts were at the morning
image

**Comment by Andrii35** [comment]
> > I guess @Andrii35 had approved this PR before another branch was merged.
> 
> Conflicts were at the morning
> image

I saw this conflict. I approved this PR, becose I make reviews and this PR works on his branch. Many PRs are approved before and it si possible, that some PRs has conflicts thereafter.  If needed i will see this PR one more time after conflict fix.

**Comment by narekacy** [comment]
@Andrii35 @vitalii-mak @Melnyk9506 
This PR is merged with dev yet.

**Comment by vitaliimak** [comment]
Again)
image

**Comment by narekacy** [comment]
> Again)
> image

Yeah, this time I went to this PR immediately after merging previous one :)

**Comment by narekacy** [comment]
@vitalii-mak @Andrii35 @Melnyk9506 
This PR is merged with dev yet.

**Review by Melnyk9506 — APPROVED** [review]

**Review by vitaliimak — APPROVED** [review]

**Review by Andrii35 — APPROVED** [review]

**Pull request merged**
