### PR TITLE
Feature 86 edit db properties

### PR DESCRIPTION
**Pull request by Melnyk9506**
database user and password changed
and the name of the database
who uses windows so need to go to pgAdmin and create such user and such database
every changes in aplication.properties you can see

### CODE REVIEW

**Review by Andrii35 — COMMENTED** [review]
Unfortunately can't run. Error message: "org.postgresql.util.PSQLException: FATAL: database "lunchtime" does not exist"

**Comment by vitaliimak** [comment]
@Andrii35 Fixed, try to remove docker container `docker container rm lunch-time-db` and run docker-compose again

**Review by Andrii35 — COMMENTED** [review]
It works, but i can't send feedback as loged user. On dev branch i can do it.

**Review by narekacy — APPROVED** [review]
Everything works

**Comment by vitaliimak** [comment]
@Andrii35 did you clear old token and relogin in new database?

**Comment by vitaliimak** [comment]
@Melnyk9506 please, merge current dev into your feature branch!

**Review by Melnyk9506 — COMMENTED** [review]
hi

**Review by vitaliimak — APPROVED** [review]

**Review by VozNick — APPROVED** [review]

**Pull request merged**
