### PR TITLE
Feature 152. About and Contact pages. narek

### PR DESCRIPTION
**Pull request by narekacy**

### CODE REVIEW

**Review by vitaliimak — CHANGES_REQUESTED** [review]
Use normal html

**Review by vitaliimak — CHANGES_REQUESTED** [review]
How this pages looks on phones
image

How your code should look (plus your styles)
```
import React, { Component } from 'react';

class About extends Component {
  render() {
    return (
      <article>
        <h1>Welcome to LunchTime Application!</h1>
        <p>
          This application is going to save your time while making restaurant order!
          We have a huge partnership network that allows you to communicate with your
          favourite restaurant faster and easier!
        </p>
        <h3>LunchTime Application is good if you want to:</h3>
        <ul>
          <li>see restaurants and events in your city;</li>
          <li>see what restaurants in your city have free tables right now;</li>
          <li>see restaurants location on the map;</li>
          <li>search dishes your like;</li>
          <li>make orders online, leave feedback for completed orders;</li>
          <li>have access to your personal profile;</li>
          <li>and so many features more;</li>
        </ul>
        <p>
          Finally, if you are restaurant owner, you are welcome
          to add your restaurant along with its information, menu and events!
        </p>
        <p>Thank you for your choice!</p>
      </article>
    );
  }
}

export default About;
```

**Comment by narekacy** [comment]
> How this pages looks on phones

Create another ask in trello to fix it.

> How your code should look (plus your styles)

Thank you.Next time i will do like this. And what's wrong with my solution and tasks requirements?

**Review by r-yevchuk — CHANGES_REQUESTED** [review]
Знімок екрану_2020-04-27_10-59-57
On smaller screens, it looks like this

**Comment by narekacy** [comment]
> On smaller screens, it looks like this

See my **[previous](https://github.com/Social-projects-Rivne/Lunch_Time/pull/80#issuecomment-619505480)** answer, please.

**Comment by r-yevchuk** [comment]
> > On smaller screens, it looks like this
> 
> See my **[previous](https://github.com/Social-projects-Rivne/Lunch_Time/pull/80#issuecomment-619505480)** answer, please.

Anyway you should have fixed it. 
It look so in my second screen with 1280x1024 resolution.

**Pull request closed without merging**
