### PR TITLE
Feature 1. Register to the system. narek

### PR DESCRIPTION
**Pull request by narekacy**
Guest can register and authorize after successful registration.
Sorry for dumb code in `Register.js`. Had no time and hurry up to our demo, so it works, despite of its length.

### CODE REVIEW

**Review by VozNick — DISMISSED** [review]

**Review by Melnyk9506 — DISMISSED** [review]

**Review by Andrii35 — CHANGES_REQUESTED** [review]
You have checkstyle error: /app/src/main/java/com/lunchtime/controllers/**PersonController.java:24**: Line is longer than 120 characters (found 128). [LineLength]

**Comment by narekacy** [comment]
> You have checkstyle error: /app/src/main/java/com/lunchtime/controllers/**PersonController.java:24**: Line is longer than 120 characters (found 128). [LineLength]

Fixed, thanks

**Review by VozNick — DISMISSED** [review]

**Review by Melnyk9506 — DISMISSED** [review]
well done

**Review by Andrii35 — APPROVED** [review]
Registration works, and i will approwe it.
But I have some validation suggestions that can be fixed later.

**Review by VozNick — APPROVED** [review]

**Review by Melnyk9506 — APPROVED** [review]

**Pull request merged**
