### PR TITLE
Feature 177. Add user response when order is successfully registered. narek

### PR DESCRIPTION
**Pull request by narekacy**
Try to make order and see response.

### CODE REVIEW

**Comment by vitaliimak** [comment]
@narekacy 
image
`tableId` - string, and you use strict comparison `===`
Also, `this.state.table` - is already `tableId`, wrong naming

Simpler
```
getTableNumber() {
    const { table, availableTables } = this.state;
    const usedTable = availableTables.find((t) => t.id === +table);
    return usedTable && usedTable.number;
  }
```
And you can rename variable `this.state.table` to `this.state.tableId` for better readability

**Comment by narekacy** [comment]
> @narekacy
> image
> `tableId` - string, and you use strict comparison `===`
> Also, `this.state.table` - is already `tableId`, wrong naming
> 
> Simpler
> 
> ```
> getTableNumber() {
>     const { table, availableTables } = this.state;
>     const usedTable = availableTables.find((t) => t.id === +table);
>     return usedTable && usedTable.number;
>   }
> ```
> 
> And you can rename variable `this.state.table` to `this.state.tableId` for better readability

Thank you very much for clear answer!

**Review by vitaliimak — COMMENTED** [review]
https://www.loom.com/share/8c422c781a814efc900b41ae345edf9a

**Comment by narekacy** [comment]
> https://www.loom.com/share/8c422c781a814efc900b41ae345edf9a

Thank you, will fix it now

**Comment by narekacy** [comment]
> > https://www.loom.com/share/8c422c781a814efc900b41ae345edf9a
> 
> Thank you, will fix it now

This goes to server part already with another date (checked in dev). So, could this be connected with smth like development or production time settings? 

image

**Comment by vitaliimak** [comment]
> This goes to server part already with another date (checked in dev). So, could this be connected with smth like development or production time settings? 

Client sends date in this format (with timezone) and server convert it in other time format

Staging server has timezone Europe/Kiev

**Comment by narekacy** [comment]
> > This goes to server part already with another date (checked in dev). So, could this be connected with smth like development or production time settings?
> 
> Client sends date in this format (with timezone) and server convert it in other time format
> 
> Staging server has timezone Europe/Kiev

I mean this isn't branch's issue. This is about some 'date/time' settings

**Comment by narekacy** [comment]
> > > This goes to server part already with another date (checked in dev). So, could this be connected with smth like development or production time settings?
> > 
> > 
> > Client sends date in this format (with timezone) and server convert it in other time format
> > Staging server has timezone Europe/Kiev
> 
> I mean this isn't branch's issue. This is about some 'date/time' settings

Fixed. But server still receives invalid value, but persists valid :)

**Review by vitaliimak — APPROVED** [review]

**Review by Melnyk9506 — APPROVED** [review]

**Review by Andrii35 — APPROVED** [review]

**Pull request merged**
